# Mandatory settings

name: Edward Bramanti
paginate: 25
url: https://bramanti.me # add your site url (format: https://example.com/)
blog_theme: dark # Or use dark

# Optional settings
heap_analytics: '7009234'
about_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the about page
discus_identifier: bramanti # Add your Disqus identifier
ga_analytics: # Add your GA Tracking Id
local_fonts: false # Change to true if you wish to use local fonts
rss_enabled: true # Change to false if not
scrollappear_enabled: true # Change to false to disable
social:
  resume: https://represent.io/ebramanti
  github: jadengore # Add your GitHub handle
  linkedin: edwardbramanti # Add your LinkedIn handle
  email: edward@bramanti.org # Add your Email address

# Important settings (change at own risk)

assets:
  features:
    automatic_img_size: false
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - vendor/
  - yarn.lock
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: /posts/page/:num/
permalink: /:title/
